#!/bin/bash

set -e

# copy user data
cp /tmp/userFiles/gitconfig ~/.gitconfig
mkdir -p ~/.mrtgitlab
cp /tmp/userFiles/mrt.cfg ~/.mrtgitlab/

source /opt/ros/jade/setup.bash

# init workspace
cd ~
mkdir ws
cd ws
mrt ws init
mrt pkg add $1
mrt catkin build --release
