#!/bin/bash

set -e

# copy user data
cp /tmp/userFiles/gitconfig ~/.gitconfig
mkdir -p ~/.mrtgitlab
cp /tmp/userFiles/mrt.cfg ~/.mrtgitlab/

source /opt/ros/jade/setup.bash

#create new workspace and build
mkdir ~/ws
cd ~/ws
mrt ws init
rm -rf src
cp -r /tmp/ws/src ./

mrt ws resolve_deps
mrt catkin build --release


