#!/bin/bash
SELF="$(readlink /proc/$$/fd/255)" || SELF="$0" # Eigener Pfad (besseres $0)
old_name=$(basename $SELF)
new_name="${old_name/"mrt_"/"mrt "}"
echo "$(tput bold)$(tput setf 1)WARNING:$(tput sgr0) '$old_name' is deprecated. Please use $(tput bold)'$new_name'$(tput sgr0) instead.'"
echo "This message will be removed in a future release."