#!/usr/bin/python

import os
import subprocess
import sys
import glob

if not "LD_LIBRARY_PATH" in os.environ or not "/opt/ros" in os.environ["LD_LIBRARY_PATH"]:
    print "ROS_ROOT not set. Source /opt/ros/<dist>/setup.bash"
    sys.exit(1)

scriptRoot = os.path.dirname(os.path.realpath(__file__))

resolve_deps = False
arguments = sys.argv[1:]

if "-h" in arguments or "--help" in arguments:
    print("mrt_catkin [-rd|--resolve-deps] [--eclipse] [--debug] [--release] <catkin parameters>\n")
    print(" -rd, --resolve-deps     Check and resolve dependencies before building workspace.")
    print(" --eclipse               Create a eclipse project.")
    print(" --debug                 Build in debug mode.")
    print(" --release               Build in release mode.")
    print(" --verbose               Compile in verbose mode.")
    print("")
    print("Additional catkin parameters:")
    subprocess.check_call(["catkin"] + arguments)
    sys.exit()

if "-rd" in arguments:
    resolve_deps = True
    arguments.remove("-rd")

if "--resolve-deps" in arguments:
    resolve_deps = True
    arguments.remove("--resolve-deps")

if "--debug" in arguments:
    arguments.remove("--debug")
    arguments.append("-DCMAKE_BUILD_TYPE=Debug")

if "--release" in arguments:
    arguments.remove("--release")
    arguments.append("-DCMAKE_BUILD_TYPE=RelWithDebInfo")

if "--verbose" in arguments:
    arguments.remove("--verbose")
    arguments.append("-v")
    arguments.append("--make-args")
    arguments.append("VERBOSE=1")

build_eclipse = False
if "--eclipse" in arguments:
    arguments.remove("--eclipse")
    build_eclipse = True
    arguments.append("--force-cmake")
    arguments.append("-GEclipse CDT4 - Unix Makefiles")

if resolve_deps:
    try:
        subprocess.check_call([os.path.join(scriptRoot, "mrt_resolve_deps")])
    except subprocess.CalledProcessError:
        print("Cannot resolve dependencies.\n")
        sys.exit(1)

subprocess.call(["catkin"] + arguments)

if build_eclipse:
    subprocess.check_call([os.path.join(scriptRoot, "mrt_set_eclipse_project_setting")])
