#!/bin/bash

if [ -z "$ROS_ROOT" ]; then
	echo "ROS_ROOT not set. Maybe forgotten to source /opt/ros/<dist>/setup.bash file."
	exit 1
fi

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

#create eclipse project
catkin_make --force-cmake -G"Eclipse CDT4 - Unix Makefiles"

#set environment variables
awk -f $(rospack find mk)/eclipse.awk build/.project > build/.project_with_env && mv build/.project_with_env build/.project

#add support for indexing
if ! [ -f build/.settings/language.settings.xml ]; then
	mkdir build/.settings
	cp "$DIR/data/template/language.settings.xml" build/.settings
fi

