#!/usr/bin/python
import subprocess
import re
import sys
import os

#read private token file
def getGitlabTokenFile():
    homeFolder = os.path.expanduser("~")
    tokenFileName = os.path.join(homeFolder, ".mrtgitlab", ".token")
    if not os.path.isfile(tokenFileName):
        subprocess.check_call(["mrt_setup_gitlab"])
    
    if not os.path.isfile(tokenFileName):
        raise RuntimeError("Internal error: gitlab file not found")
        
    return tokenFileName

def main():
    if len(sys.argv) == 1 or len(sys.argv) > 4:
        print("Usage: mrt_check_pkg [package name] <url>")
        sys.exit(1)
    
    tokenFileName = getGitlabTokenFile()
    scriptPath = os.path.dirname(os.path.realpath(__file__))
    
    if len(sys.argv) > 1 and sys.argv[1] == "local":
        subprocess.check_call(["python", os.path.join(scriptPath, "docker_check_pkg.py"), tokenFileName] + sys.argv[2:])
    else:
        subprocess.check_call(["python", os.path.join(scriptPath, "docker_check_pkg_remote.py"), tokenFileName] + sys.argv[1:])
    

if __name__ == "__main__":
    main()
