#!/bin/bash
set -e

USER_ID="$1"
USER_NAME="$2"
GROUP_ID="$3"
GROUP_NAME="$4"
SCRIPT_NAME="$5"

echo "$USER_NAME    ALL = NOPASSWD: /usr/bin/apt-get" | sudo tee -a /etc/sudoers &> /dev/null

addgroup -q --gid $GROUP_ID $GROUP_NAME
useradd -ms /bin/bash --gid $GROUP_ID --uid $USER_ID $USER_NAME
gosu $USER_ID:$GROUP_ID "$5" "$6"
